global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'safe-temporary-db-access'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'safe-temporary-db-access'
    basic_auth:
      username: prometheus
      password: secret123
    honor_labels: true