# Run all components without app - when we want to use for local development with running application in IntellijIDEA
services:
  postgres1:
    image: postgres:16
    container_name: safe-access-postgres1
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test1
    ports:
      - "5432:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  postgres2:
    image: postgres:16
    container_name: safe-access-postgres2
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test2
    ports:
      - "5433:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:6
    container_name: safe-access-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  prometheus:
    image: prom/prometheus:latest
    container_name: safe-access-prometheus
    env_file:
      - ./../.env
    volumes:
      - prometheus-data:/prometheus
      - ./../../observability/prometheus.local.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: safe-access-grafana
    env_file:
      - ./../.env
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=superStrongPassword123!
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/system-overview.json
    volumes:
      - grafana-data:/var/lib/grafana
      - ./../../observability/grafana/provisioning:/etc/grafana/provisioning
      - ./../../observability/grafana/dashboards:/var/lib/grafana/dashboards
      - ./../../observability/grafana/provisioning/dashboards/business:/etc/grafana/provisioning/dashboards/business
      - ./../../observability/grafana/provisioning/dashboards/micrometer:/etc/grafana/provisioning/dashboards/micrometer
      - ./../../observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./../../observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pgdata1:
  pgdata2:
  mongodata:
  grafana-data:
  prometheus-data: