# Run all components with app
services:
  postgres:
    image: postgres:16
    container_name: safe-access-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:6
    container_name: safe-access-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  app:
    image: ghcr.io/camilyed/safe-temporary-db-access:latest
    container_name: safe-access-app
    depends_on:
      - postgres
      - mongo
    ports:
      - "8080:8080"
    env_file:
      - ./../.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./../jwt/ec256-public.der:/app/ec256-public.der

volumes:
  pgdata:
  mongodata: