version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: safe-access-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: safe-access-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  app:
    image: ghcr.io/your-username/safe-temporary-db-access:latest
    container_name: safe-access-app
    depends_on:
      - postgres
      - mongo
    ports:
      - "8080:8080"
    environment:
      TEST1_DB_URL: jdbc:postgresql://postgres:5432/test1
      TEST1_DB_USERNAME: admin
      TEST1_DB_PASSWORD: admin
      MONGO_URL: mongodb://mongo:27017
      PUBLIC_KEY_LOCATION: /app/ec256-public.der
    volumes:
      - ./devtools/jwt/ec256-public.der:/app/ec256-public.der

volumes:
  pgdata:
  mongodata: