# Run all components with app
services:
  postgres:
    image: postgres:16
    container_name: safe-access-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:6
    container_name: safe-access-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  app:
    image: ghcr.io/camilyed/safe-temporary-db-access:latest
    container_name: safe-access-app
    depends_on:
      - postgres
      - mongo
    ports:
      - "8080:8080"
    env_file:
      - ./../.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./../jwt/ec256-public.der:/app/ec256-public.der

  prometheus:
    image: prom/prometheus:latest
    container_name: safe-access-prometheus
    env_file:
      - ./../.env
    volumes:
      - ./../../observability/prometheus.compose.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: safe-access-grafana
    env_file:
      - ./../.env
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/system-overview.json
    volumes:
      - grafana-data:/var/lib/grafana
      - ./../../observability/grafana/provisioning:/etc/grafana/provisioning
      - ./../../observability/grafana/dashboards:/var/lib/grafana/dashboards
      - ./../../observability/grafana/provisioning/dashboards/business:/etc/grafana/provisioning/dashboards/business
      - ./../../observability/grafana/provisioning/dashboards/micrometer:/etc/grafana/provisioning/dashboards/micrometer
      - ./../../observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./../../observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pgdata:
  mongodata:
  grafana-data: